### ISSUE TITLE
LiDAR simulation in Gazebo

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/MAVs#4]
# New Feature
This feature will leverage Gazebo to simulate a LiDAR. With that vehicle dynamics will simulated by Chrono with https://github.com/CPFL/Autoware/issues/1107.

# Status 
With [this commit](https://github.com/huckl3b3rry87/Autoware/commit/b2ca113c3ad926fbd9a412262b022e032bec5994) a HMMWV vehicle is visualized in Gazebo along with an obstacle. By running
```
roslaunch mavs_gazebo move_hmmwv.jl
```
Gazebo pops up and the vehicle moves along the y direction past an obstacle while publishing lidar points as
```
mavs/mavs_gazebo$ rostopic type lidar_points
sensor_msgs/PointCloud2
```
# TODO 
- [x] 1) make make it possible to initialize with other config files for vehicle and obstacle position
- [ ]  2) fix gazebo and RViz views on hmmwv
- [x]  3) fix display issue on the tires
- [x]  4) add speed of obstacles in Gazebo
- [x]  5) add multiple obstacles
- [x]  6) use the robot name parametrically in all files
- [x]  7) add in an option to update the state of the vehicle based off of /state/ parameter
- [ ]  8) add in an option to pause the simulation before it starts 	
- [ ] 9) add in an option to convert the format of the data to PointCloud
- [ ] 10) add in an option to not simulate Gazebo
- [ ] 11) add in an option to pass the reference frame of the vehicle and the lidar

**Comment by huckl3b3rry87** [comment]
@tqshao for you to test this with the [obstacle_detector](https://github.com/CPFL/Autoware/issues/1109) package, you will need to complete task 11) and task 9). I started both of these and there is an example of task 11) being done in my [AVExamples.jl](https://github.com/huckl3b3rry87/AVExamples.jl/tree/master/docs/src/tutorials/VLP16_ws/src) package. We should add the point_cloud_converter package for doing this conversion, if it is not already in Autoware (need to check). Can you please take care of at least these two tasks from the list above?

**Comment by huckl3b3rry87** [comment]
Given [this commit](https://github.com/huckl3b3rry87/Autoware/commit/d763c8536a533e23b6538bd1c361782b22f76c4d) TODO items 1,3,4,5,6,7 are complete.

It can be tested with:
```
roslaunch mavs_gazebo demo.launch
```

**Comment by huckl3b3rry87** [comment]
Program to follow the vehicle
http://osrf-distributions.s3.amazonaws.com/gazebo/api/dev/GuiEvents_8hh_source.html

http://answers.gazebosim.org/question/8437/how-to-make-the-camera-track-a-moving-robot/
