### ISSUE TITLE
Setup the A* Path Planner Algorithm in Gazebo

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/MAVs#5]
# Feature
Setup the [A* Path Planning Algorithm](https://github.com/CPFL/Autoware/tree/master/ros/src/computing/planning/motion/packages/astar_planner) (or others if there is a better one) in Gazebo. 

# TODO 
- [x] 1) figure out the topics that this node subscribes and publishes to
- [x] 2) establish/ensure connection to this node and its subscribed topics
- [ ] 3) test using system described in https://github.com/JuliaMPC/MAVs/issues/7

**Comment by huckl3b3rry87** [comment]
@sumjos is this done?
