### ISSUE TITLE
Integrate Moving Obstacle Detector

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/MAVs#6]
# Feature
Integrate the ROS package [obstacle_detector](https://github.com/tysik/obstacle_detector) into Autoware.

# Motivation
The motication (and please let me know if I am wrong) is that (again from what I understand) the current obstacle detection algoritms in Autoware do not predict the, postion (x,y), velocty (x,y),  and size (assuming circular obstacles) . 

# TODO
 - [x] Install the obstacle_detector package as a submodule.
 - [x] Make an obstacle_detector launch file so that it subscribes the point cloud topic from Autoware.
 - [x] Test the performance of the obstacle_detector package.
- [x] Set up obstacle_detector as [per this](https://github.com/tysik/obstacle_detector)
- [x] Set up and test obstacle_detector as an example in Gazebo [launch file](https://github.com/huckl3b3rry87/MAVs.jl/blob/master/catkin_ws/src/mavs_gazebo/launch/hmmwv.launch#L42), stationary platform
- [x] Set up and test obstacle_detector as an example in Gazebo [some code for this and the above item](https://github.com/huckl3b3rry87/MAVs.jl/blob/master/catkin_ws/src/obstacle_detector/launch/mavs.launch), moving platform
- [ ] set up obstacle detector_package with a real VLP16 [some code for this here](https://github.com/huckl3b3rry87/AVExamples.jl/tree/master/docs/src/tutorials/VLP16_ws/src)
